### ISSUE TITLE
SSR rendering not working for https

### ISSUE THREAD

**Issue by prindacerk** [ganatan/angular11-app#13]
I am using your project as a starting template for my web app.

One thing I noticed during your source code is that the https is not serving the webpage content from server side. If I access the url as http, I can see the server side rendered content of the page in view source. 

But if I try to do the same via https, I can't see the source. The content is being loaded only in client side. This also affects SEO because the title/description are all not there in https.

Do you have any suggestion on how I can rectify this issue? Would be great if you can include that solution option.

**Comment by mshenawy** [comment]
Why SSR is not working ?

**Comment by prindacerk** [comment]
I cannot identify the reason why **https** is not working. It works fine in http.

**Comment by infinitai** [comment]
This seems to be fine now. Working in the current version. Can close this.

**Comment by prindacerk** [comment]
This seems to be fine now. Working in the current version. Can close this.
